[package]
name = "horned-owl"
version = "0.9.1-alpha.0"
authors = ["Phillip Lord <phillip.lord@russet.org.uk>"]
description = "Library and Command Line tools for OWL Ontologies"

repository = "https://github.com/phillord/horned-owl"

keywords = ["xml", "ontology", "OWL", "command"]
categories = ["command-line-utilities", "parsing",
              "rendering", "science", "data-structures"]

license = "LGPL-3.0"
edition = "2018"

[dependencies]
curie = "0.0.8"
curl = "0.4.34"
clap = "2.31.2"
enum_meta = "0.6.0"
failure = "0.1.2"
lazy_static="1.4.0"
log = {version="0.4.8"}
quick-xml="0.12.4"
indexmap="1.0.2"
rio_api={git="https://github.com/oxigraph/rio.git"}
rio_xml={git="https://github.com/oxigraph/rio.git"}
# rio_api={path="./rio/api"}
# rio_xml={path="./rio/xml"}


[dev-dependencies]
assert_cmd = "0.10"
bencher = "0.1.4"
env_logger = "0.7.1"
mktemp = "0.3.1"
predicates = "1"
pretty_assertions = "0.6.1"
slurp = "1.0.1"

[profile.release]
debug = true

[[bench]]
name = "horned"
harness = false
