[package]
name = "horned-owl"
version = "0.1.0"
authors = ["Phillip Lord <phillip.lord@russet.org.uk>"]

[dependencies]
bimap = "0.1.3"

quick-xml="0.11.0"
curie = "0.0.5"
clap = "2.31.2"

[dev-dependencies]
bencher = "0.1.4"
mktemp = "0.3.1"

[[bench]]
name = "horned"
harness = false